// File: frontend/src/service-worker.js
/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from "workbox-core";
import { ExpirationPlugin } from "workbox-expiration";
import { precacheAndRoute, createHandlerBoundToURL } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { StaleWhileRevalidate } from "workbox-strategies";

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp("/[^/?]+\\.[^/]+$");
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }) => {
    console.log("Request URL:", url.pathname); // Debug log
    // If this isn't a navigation, skip.
    if (request.mode !== "navigate") {
      return false;
    }

    // If this is a URL that starts with /_, skip.
    if (url.pathname.startsWith("/_")) {
      return false;
    }

    // If this looks like a URL for a resource, because it contains // a file extension, skip.
    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    }

    // Skip if the request is for an API
    //memastikan bahwa permintaan API tidak ditangani oleh index.html.
    if (url.pathname.startsWith("/api/")) {
      return false;
    }

    // Return true to signal that we want to use the handler.
    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + "/index.html")
  //mengatur caching untuk navigasi menuju index.html (App Shell)
);

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/

// menggunakan Workbox untuk menangani caching dengan strategi StaleWhileRevalidate dan ExpirationPlugin,
// yang merupakan cara efisien untuk mengelola cache secara otomatis dan menjaga ukuran cache tetap terkendali. Ini sangat umum digunakan dalam PWAs.
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) =>
    url.origin === self.location.origin && url.pathname.endsWith(".png"), // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: "images",
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});

// Any other custom service worker logic can go here.

self.addEventListener("install", (event) => {
  console.log("Service Worker installing.");
  // Tambahkan logika caching atau hal lainnya di sini jika diperlukan
});

self.addEventListener("activate", (event) => {
  console.log("Service Worker activating.");
  // Logika untuk aktivasi, seperti membersihkan cache lama
});

//Listener ini akan menangani notifikasi yang diterima dari server. Notifikasi ini akan muncul pada perangkat pengguna jika push notification diterima.
self.addEventListener("push", function (event) {
  console.log("Push event received:", event);

  let data = {};

  try {
    data = event.data.json();
    console.log("Push data:", data);
  } catch (e) {
    console.error("Error parsing JSON:", e);
    data = { title: "Test push", body: "Default body if JSON fails" }; // Gunakan default jika JSON gagal
  }

  const title = data.title || "Default Title";
  const options = {
    body: data.body || "Default Body",
    icon: data.icon || "icon.png",
    badge: data.badge || "badge.png",
    actions: [
      { action: "open", title: "Buka Aplikasi" },
      { action: "dismiss", title: "Tutup" },
    ],
  };

  event.waitUntil(self.registration.showNotification(title, options));
});

self.addEventListener("notificationclick", function (event) {
  if (event.action === "open") {
    self.clients.openWindow("/undangan"); // Misalnya buka aplikasi
  }
  event.notification.close(); // Tutup notifikasi setelah aksi
});

self.addEventListener("fetch", (event) => {
  // Debug fetch event
  console.log("Fetch event for", event.request.url);

  // Ensure requests for API routes are not handled by the service worker
  if (event.request.url.includes("/api/")) {
    return;
  }

  // Default fetch handling for other requests
  event.respondWith(
    caches.match(event.request).then((response) => {
      return response || fetch(event.request);
    })
  );
});
